### ISSUE TITLE
Can't add firebase-php to Symfony 3 

### ISSUE THREAD

**Issue by argoitz** [kreait/firebase-php#112]
#### 1. Which version of `kreait/firebase-php` are you using?
2.3.1

#### 2. Which version of PHP are you using?
7.0

#### 3. What's the issue?

Im triing to add firebase-php to my symfony 3 project as say in this guide (https://github.com/kreait/firebase-php/blob/69496a13084710ff36d693439297e778dde178f0/doc/symfony.md) and i get this error:

> There is no extension able to load the configuration for "firebase.config" (in /var/www/html/app/config/config.yml). Looked for namespace "firebase.config", found "framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "easy_admin", "fos_user", "fos_rest", "nelmio_cors", "nelmio_api_doc", "jms_serializer", "debug", "web_profiler", "sensio_distribution" in /var/www/html/app/config/config.yml (which is being imported from "/var/www/html/app/config/config_dev.yml").

#### 4. Code that lead to the issue

config.yml
```
#FIREBASE
firebase:
    class: Kreait\Firebase\Firebase
    arguments: ["%firebase_databaseURL%", '@firebase.config']

firebase.config:
    class: Kreait\Firebase\Configuration
    calls:
        - ['setFirebaseSecret', ['%firebase_apiKey%']]
...
```

Parameters.yml
```
    firebase_apiKey: <my_code>
    firebase_databaseURL: https://<myurl>.firebaseio.com
...
```

Controller
```
namespace CronBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\Tools\Pagination\Paginator;

class CronController  extends FOSRestController implements ClassResourceInterface
{

    /**
     * @Route("/cron/firebase"), name="api_login" }
     */

    public function firebaseAction(Request $request){
          echo "HELLO";
          exit;
    }
```

**[UPDATE]**
I add config.yml content to config_dev.php and the error change a little:

> There is no extension able to load the configuration for "firebase" (in /var/www/html/app/config/config_dev.yml). Looked for namespace "firebase", found "framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "easy_admin", "fos_user", "fos_rest", "nelmio_cors", "nelmio_api_doc", "jms_serializer", "debug", "web_profiler", "sensio_distribution"

Please help.
Thank you.
