### ISSUE TITLE
how to retrieve data from child of child 

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#34]
hello 
i have driver table  like that 
driver=>
```
            -KQBWNv6sZWuh-x9QYUS
                    city:  "value"
                    companyID:   "-KQBWNv6sZWuh-x9QYUS"
                    createdAt: 
                    driverFacebookTokenID: 
                    driverLicenseNumber: 11231231
                    driverPhoto: "iamge"
                    firstName:"waleed"
                    insuranceCertificate: 
                    status: 0
                    uid: "-KQBWNv6sZWuh-h9QYUS"
                    updatedAt: "asdasd"
                    vehicle: "vicle id"

             -KQBWNv6sZWuh-x9QYaa
                    firstName:"waleed"
                    insuranceCertificate: 
                    status: 0
                    uid: "-KQBWNv6sZWuh-h9QYUS"

```
I try to build query to get drivers where sub child uid = eg.(-KQBWNv6sZWuh-h9QYUS)
how to fetch that without get all data for loop it to get my records 
note : i am using version 1
regards
